import { paymentsApi } from "../index.js";

 export const processPayment=async(token, amount)=> {
    const requestBody = {
      sourceId: token, // This is the token generated by Square.js in the frontend
      amountMoney: {
        amount: amount*120, // amount in cents
        currency: 'USD',
      },
      idempotencyKey: new Date().getTime().toString(), // A unique key to avoid double charges
    };
  
    try {
      const { result } = await paymentsApi.createPayment(requestBody);
      // console.log('Payment Result:', result);
      return result;
    } catch (error) {
      throw new Error(error);
    }
}

  